name: Docker Build and Deploy

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Permet de lancer le workflow manuellement depuis l'interface GitHub

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      - name: Build and test
        uses: docker/build-push-action@v4
        with:
          context: .
          load: true
          tags: my-website:test
          
      - name: Test container
        run: |
          docker run -d --name test-container -p 8080:80 my-website:test
          sleep 5
          curl -s --retry 10 --retry-connrefused http://localhost:8080 | grep -q "Mon Projet"
          docker stop test-container
          
      - name: Build and push
        if: github.event_name != 'pull_request'
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/website-bootstrap:latest
          
      - name: Image digest
        if: github.event_name != 'pull_request'
        run: echo ${{ steps.docker_build_push.outputs.digest }}
